name: _deploy

on:
  workflow_call:

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build App
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm i
      - run: npm ci
      - run: npm run build

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "breaking" 
          minor_pattern: "feat"
          version_format: "v${major}.${minor}.${patch}-prerelease${increment}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push prerelase
        id: docker_push_prerelease
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/chatpad-plus:${{ steps.versioning.outputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version_tag }}
          release_name: Release ${{ steps.versioning.outputs.version_tag }}
          draft: false
          prerelease: ${{ github.ref_name != github.event.repository.default_branch }}

      - id: ref
        shell: bash
        run: |
          echo "refspec=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.versioning.outputs.version_tag }}
          commit: ${{ steps.ref.outputs.refspec }}

      - name: Push release
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/chatpad-plus:${{ steps.versioning.outputs.version_tag }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/chatpad-plus:latest