name: _deploy

on:
  workflow_call:


jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "breaking" 
          minor_pattern: "feat"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: rainingdreams/chatpad-plus:${{ steps.semvers.outputs.patch }}
          # tags: rainingdreams/chatpad-plus

      - name: Image digest
        run: echo ${{ steps.docker_push.outputs.digest }}