name: _deploy

on:
  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
            apiToken: ${{ secrets.CF_KEY }}
            accountId: ${{ secrets.CF_ID }}
            projectName: chatpad-plus
            directory: ./dist
            # Optional: Switch what branch you are publishing to.
            # By default this will be the branch which triggered this workflow
            # branch: main