name: ci_cd
on:
  push:
    branches:    
      - main
      - 'fix/**'
      - 'feat/**'

  pull_request:


permissions:
  contents: write

jobs:

  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  push:
    needs: [ build ]
    uses: ./.github/workflows/_push.yml
    secrets: inherit

  deploy:
    needs: [ build ]
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit